### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
quant_bit: 4
use_qlora : true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: alpaca
template: llama3
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: work_dir/llama3-8b/qlora/sft/
save_strategy: steps
save_steps: 500
save_total_limit: 5
overwrite_output_dir: true

# logger settings
logging_steps: 10
report_to: wandb
wandb_project: llamatuner
wandb_run_name: llama3-8b_qlora_sft

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
gradient_checkpointing: True
num_train_epochs: 3.0
learning_rate: 1.0e-4
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true

### eval
eval_dataset_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
