### model
model_name_or_path: Qwen/Qwen2.5-0.5B
trust_remote_code: true


### method
stage: pt
do_train: true
finetuning_type: full

### ddp
ddp_timeout: 180000000

### dataset
dataset: c4_demo
eval_dataset: c4_demo
template: qwen
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 8

### output
output_dir: work_dir/pretrain/qwen2.5-0.5b/
save_strategy: steps
save_steps: 500
save_total_limit: 5
overwrite_output_dir: true

# logger settings
logging_steps: 10
report_to: wandb
wandb_project: llamatuner
wandb_run_name: qwen2.5-0.5b_pretrain

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
gradient_checkpointing: True
num_train_epochs: 3.0
optim: adamw_torch
learning_rate: 1.0e-4
lr_scheduler_type: cosine
weight_decay: 0.01
warmup_ratio: 0.1
fp16: true

### eval
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
