### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full

### ddp
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: alpaca
template: llama3
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: work_dir/llama3-8b/full/sft
wandb_project: llamatuner
wandb_run_name: llama3-8b_full_sft_alpaca
logging_steps: 10
save_strategy: steps
save_total_limit: 5
save_steps: 500
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
num_train_epochs: 3.0
optim: adamw_torch
learning_rate: 1.0e-4
lr_scheduler_type: cosine
weight_decay: 0.01
warmup_ratio: 0.1
fp16: true

### eval
eval_data_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
