### model
model_name_or_path: Qwen/Qwen1.5-0.5B

### method
stage: sft
do_train: true
finetuning_type: full

### dataset
dataset: alpaca
template: qwen
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: work_dir/full/alpaca_qwen_full
save_strategy: steps
save_steps: 500
save_total_limit: 5
overwrite_output_dir: true

# logger settings
logging_steps: 10
report_to: wandb
wandb_project: llamatuner
wandb_run_name: qwen_full_sft_alpaca

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
gradient_checkpointing: True
optim: adamw_torch
learning_rate: 1.0e-4
lr_scheduler_type: cosine
weight_decay: 0.01
warmup_ratio: 0.1
num_train_epochs: 3.0
fp16: true

### ddp
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z3_config.json

### eval
eval_dataset_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
