### model
model_name_or_path: Qwen/Qwen1.5-0.5B

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: q_proj,v_proj

### dataset
dataset: alpaca
template: qwen
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: work_dir/lora/sft
save_strategy: steps
save_steps: 500
save_total_limit: 5
overwrite_output_dir: true

# logger settings
logging_steps: 10
report_to: wandb
wandb_project: llamatuner
wandb_run_name: alpaca_qwen_lora-sft

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
gradient_checkpointing: True
optim: adamw_torch
learning_rate: 1.0e-4
lr_scheduler_type: cosine
weight_decay: 0.0
warmup_ratio: 0.1
num_train_epochs: 3.0
fp16: true
ddp_timeout: 180000000

### eval
eval_dataset_size: 0.1
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 500
