python tools/train_lora.py \
    --model_name_or_path facebook/opt-125m \
    --dataset_cfg ./data/run_test.yaml \
    --output_dir work_dir/lora-finetune \
    --wandb_project llamatuner \
    --wandb_run_name alpaca_opt-125m_lora-finetune \
    --num_train_epochs 3 \
    --max_train_samples 200 \
    --max_eval_samples 200 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "steps" \
    --save_strategy "steps" \
    --save_steps 1 \
    --save_steps 1 \
    --save_total_limit 5 \
    --logging_steps 1 \
    --learning_rate 1e-4 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --optim "adamw_torch" \
    --lr_scheduler_type "cosine" \
    --gradient_checkpointing True \
    --trust_remote_code \
    --model_max_length 1024 \
    --do_train \
    --do_eval
